# Language Servers
# ------------------------------------------------------------------------------

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.clangd]
command = "clangd"

[language-server.gleam]
command = "gleam"
args = ["lsp"]

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]
config = { provideFormatter = true }

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]
config = {}

[language-server.buck2-lsp]
command = "buck2"
args = ["lsp"]

# Grammars
# ------------------------------------------------------------------------------

[[grammar]]
name = "ini"
source = { git = "https://github.com/justinmk/tree-sitter-ini", rev = "4d247fb876b4ae6b347687de4a179511bf67fcbc" }

# Languages
# ------------------------------------------------------------------------------

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "c"
auto-format = false
language-servers = ["clangd"]

[[language]]
name = "gleam"
auto-format = false
language-servers = ["gleam"]

[[language]]
name = "go"
auto-format = false
language-servers = ["gopls"]

[[language]]
name = "python"
auto-format = false
language-servers = ["pyright", "ruff"]
roots = [".", "pyproject.toml", "pyrightconfig.json", "requirements.txt"]

[[language]]
name = "starlark"
auto-format = false
file-types = ["bzl", { glob = "BUCK" }]
language-servers = ["buck2-lsp"]
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "json"
auto-format = false
language-servers = ["vscode-json-language-server"]
file-types = [
  "json",
  "jsonc",
  "arb",
  "ipynb",
  "geojson",
  "gltf",
  "webmanifest",
  "flake.lock",
  ".babelrc",
  ".bowerrc",
  ".jscrc",
  "js.map",
  "ts.map",
  "css.map",
  ".jslintrc",
  "jsonld",
  ".vuerc",
  "composer.lock",
  ".watchmanconfig",
]
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "toml"
auto-format = false
language-servers = ["taplo"]
file-types = ["toml", "poetry.lock", "Cargo.lock"]
comment-token = "#"

[[language]]
name = "yaml"
auto-format = false
language-servers = ["yaml-language-server"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "html"
auto-format = false
language-servers = ["vscode-html-language-server"]

[[language]]
name = "scss"
auto-format = false

[[language]]
name = "ini"
scope = "source.ini"
file-types = ["ini", { glob = ".buckconfig" }]
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }
